version: 1
jobs:
  deployFunctions:
    steps:
      - npm i -g zcatalyst-cli
      - cd /catalyst/functions/trigger_connection_server_claude && npm i
      - cd /catalyst/functions/trigger_on_demand_server_claude && npm i
      - >-
        catalyst deploy --only
        functions:trigger_connection_server_claude,functions:trigger_on_demand_server_claude
stages:
  - name: deploy
    jobs:
      - deployFunctions